version: "3.1"

services:
  db:
    container_name: database
    image: postgres
    environment:
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_USER: $DB_USER
      POSTGRES_DB: $DB_NAME
    restart: always
    ports:
      - "5432:5432"
    networks:
      - botnet
    env_file:
      - ".env"
    volumes:
      - ./pgdata:/var/lib/postgresql

  redis:
    container_name: redis
    image: redis
    command: redis-server --port $R_PORT --save 20 1 --loglevel warning
    restart: always
    env_file:
      - ".env"
    volumes:
      - ./cache:/data
    networks:
      - botnet


  tg_bot:
    container_name: bot
    build:
      context: .
    command: python main.py
    restart: always
    networks:
      - botnet
    env_file:
      - ".env"
    volumes:
      - .:/src
    depends_on:
      - db
      - redis




networks:
  botnet:
    driver: bridge